#!/usr/bin/env python3
"""Query owned addresses against a local SQLite UTXO balance index."""

from __future__ import annotations

import argparse
import json
import sqlite3
import time
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read owned addresses file and output only positive-balance addresses "
            "using a local SQLite index."
        )
    )
    parser.add_argument(
        "--addresses-file",
        type=Path,
        required=True,
        help="Input file: JSONL with `address` or one-address-per-line text.",
    )
    parser.add_argument(
        "--db",
        type=Path,
        default=Path("./utxo_balance_index.sqlite3"),
        help="SQLite index generated by build_utxo_balance_index.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("./positive_balance_wallets_from_index.jsonl"),
        help="Output JSONL path.",
    )
    parser.add_argument(
        "--progress-every",
        type=int,
        default=100_000,
        help="Print progress every N checked addresses.",
    )
    return parser.parse_args()


def parse_addresses(path: Path) -> list[str]:
    seen: set[str] = set()
    addresses: list[str] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            raw = line.strip()
            if not raw:
                continue

            address = ""
            try:
                payload = json.loads(raw)
                if isinstance(payload, dict):
                    address = str(payload.get("address", "")).strip()
                elif isinstance(payload, str):
                    address = payload.strip()
            except json.JSONDecodeError:
                address = raw

            if not address or address in seen:
                continue
            seen.add(address)
            addresses.append(address)
    return addresses


def main() -> None:
    args = parse_args()
    if args.progress_every <= 0:
        raise SystemExit("--progress-every must be positive.")
    if not args.addresses_file.exists():
        raise SystemExit(f"Addresses file not found: {args.addresses_file}")
    if not args.db.exists():
        raise SystemExit(f"SQLite index not found: {args.db}")

    addresses = parse_addresses(args.addresses_file)
    if not addresses:
        raise SystemExit("No addresses found in addresses-file.")
    print(f"Loaded {len(addresses)} unique owned address(es).")

    conn = sqlite3.connect(args.db)
    cur = conn.cursor()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    started = time.monotonic()
    found = 0

    with args.output.open("w", encoding="utf-8") as out:
        for idx, address in enumerate(addresses, start=1):
            cur.execute(
                "SELECT balance_sats FROM utxo_balances WHERE address = ?;",
                (address,),
            )
            row = cur.fetchone()
            if row is None:
                continue
            sats = int(row[0])
            if sats <= 0:
                continue

            record = {
                "address": address,
                "balance_sats": sats,
                "balance_btc": f"{sats / 100_000_000:.8f}",
            }
            out.write(json.dumps(record, ensure_ascii=True) + "\n")
            found += 1

            if idx % args.progress_every == 0:
                elapsed = max(time.monotonic() - started, 0.001)
                print(
                    f"Checked {idx}/{len(addresses)} addresses "
                    f"({idx / elapsed:.2f} checks/s), positives={found}"
                )

    conn.close()
    elapsed = max(time.monotonic() - started, 0.001)
    print(
        f"Done. Checked {len(addresses)} addresses in {elapsed:.1f}s "
        f"({len(addresses) / elapsed:.2f} checks/s)."
    )
    print(f"Positive-balance addresses: {found}. Output: {args.output.resolve()}")


if __name__ == "__main__":
    main()
